/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallToActionComponent: typeof import('./src/components/CallToActionComponent.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderSectionComponent: typeof import('./src/components/HeaderSectionComponent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ImageGalleryComponent: typeof import('./src/components/ImageGalleryComponent.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    PdfViewerComponent: typeof import('./src/components/PdfViewerComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubNavComponent: typeof import('./src/components/SubNavComponent.vue')['default']
  }
}
