/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtividadeCardComponent: typeof import('./src/components/AtividadeCardComponent.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    CertificacaoCardComponent: typeof import('./src/components/CertificacaoCardComponent.vue')['default']
    ComponenteCard: typeof import('./src/components/ComponenteCard.vue')['default']
    ComponenteCardDoacao: typeof import('./src/components/ComponenteCardDoacao.vue')['default']
    ComponenteChamadaAcao: typeof import('./src/components/ComponenteChamadaAcao.vue')['default']
    ComponenteGaleriaImagens: typeof import('./src/components/ComponenteGaleriaImagens.vue')['default']
    ComponenteNavegacao: typeof import('./src/components/ComponenteNavegacao.vue')['default']
    ComponenteRodape: typeof import('./src/components/ComponenteRodape.vue')['default']
    ComponenteSecaoCabecalho: typeof import('./src/components/ComponenteSecaoCabecalho.vue')['default']
    ComponenteSecaoConteudo: typeof import('./src/components/ComponenteSecaoConteudo.vue')['default']
    ComponenteSecaoTitulo: typeof import('./src/components/ComponenteSecaoTitulo.vue')['default']
    ComponenteVisualizadorPdf: typeof import('./src/components/ComponenteVisualizadorPdf.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Image: typeof import('primevue/image')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ParceirosComponent: typeof import('./src/components/ParceirosComponent.vue')['default']
    ProfissionalCardComponent: typeof import('./src/components/ProfissionalCardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
